[package]
name = "hvm-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "hvml"
path = "src/lib.rs"

[[bin]]
name = "hvml"
path = "src/main.rs"
required-features = ["cli"]

[profile.release]
lto = true

[features]
default = ["cli"]
cli = ["dep:clap"]

[dependencies]
chumsky = "= 1.0.0-alpha.4"
clap = { version = "4.4.1", features = ["derive"], optional = true }
highlight_error = "0.1.1"
hvm-core = { git = "https://github.com/HigherOrderCO/hvm-core" }
indexmap = "2.2.3"
itertools = "0.11.0"
logos = "0.13.0"

[dev-dependencies]
insta = "1.34.0"
stdext = "0.3.1"
walkdir = "2.3.3"
