[package]
name = "hvm-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "hvm_lang"

[[bin]]
name = "hvm-lang"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["dep:clap", "dep:byte-unit"]
nums = []

[dependencies]
anyhow = "1.0.72"
ariadne = "0.3.0"
bimap = "0.6.3"
byte-unit = { version = "4.0.19", optional = true }
chumsky = "1.0.0-alpha.4"
clap = { version = "4.4.1", features = ["derive"], optional = true }
derive_more = "0.99.17"
hvm-core = { git = "https://github.com/HigherOrderCO/hvm-core.git" }
#hvm-core = { path = "../hvm-core/rust" }
itertools = "0.11.0"
logos = "0.13.0"
shrinkwraprs = "0.3.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
stdext = "0.3.1"
walkdir = "2.3.3"
