blank_issues_enabled: false
contact_links: 
    - name: HVM Related Issues
      url: https://github.com/HigherOrderCO/HVM/issues/new/choose
      about: For HVM related Issues, please Report them on the HVM repository.
